### ISSUE TITLE
Multiple scripts at once

### ISSUE THREAD

**Issue by Shawn9347** [brianspilner01/media-server-scripts#10]
Hello, 

We talked earlier about your script. I know this is not really the place to ask but the people on bazarr discord en github are really unfriendly. 

Would you happen to know how to run multiple custom post processing commands in bazarr?
I am using your script of course ;) but I also want to synchonize my subtitles. The built in sync feature just doesn't work so that's no option. Been trying to get it working with help on discord for about 14 hours non stop now. So running two commands at once is really my last resort. 

You would make my day if you can help me. 2 minutes till midnight omg I've been debugging since 9 am. Good night.

**Comment by brianspilner01** [comment]
No problem at all, there's a couple of ways you could make that work! The easiest is probably to make your own short script (don't be intimidated) that simply calls the other two scripts one by one. Make an empty text file, say /config/bazarr.sh, then edit it to include the two separate commands and put each on two lines. Firstly in bazarr as the post-processing command you would put something like `/config/bazarr.sh "{{subtitles}}" "{{episode}}" --`

This will pass {{subtitles}} into your bazarr.sh script as the first argument, so within that script it will be available as `$1`. Likewise, {{episode}} will be available as `$2`. Put `#!/bin/bash` on the first line to specify what type of script it is (a bash script). So your finished script might end up like the following:

```
#!/bin/bash

/config/sub-clean.sh "$1"
ffsubsync "$2" -i "$1" -o "$1.synced.srt"
```

Replace the ffsubsync line with something similar to what you were inputting to the bazarr post processing field before (but use $1 or $2 etc as appropriate instead of {{subtitles}} or {{episode}} or whatever you may have been using before), I can't say exactly what you should have because I'm not too sure what you're using. Hopefully that works for you!

**Comment by Shawn9347** [comment]
Hey man, 
Thank you.
I kinda figured it out myself already xD. But I made some crazy complicated script and I'm still not sure if it even works. This clears things up a little. 

I'll let you know if I can finally properly synchonize my subtitles along with your AWESOME script. If so, you're the man. 

Is there another way I can contact you maybe through discord? For the future ;)

**Comment by Shawn9347** [comment]
I tried the script. 

![image](https://user-images.githubusercontent.com/48714886/114284743-5e003600-9a52-11eb-95d9-3109e5b982f0.png)

when I comment out the sub clean and ffsubsync it does actually show the echo in bazarr logs. When uncomment the commands it says:

![image](https://user-images.githubusercontent.com/48714886/114284766-7e2ff500-9a52-11eb-977d-ca741c2a7222.png)

Any idea why this might happen? When I echo the $1 variable it shows the full subtitle path so nothing wrong with that. 
When I run the script manually and pass along the arguments it does fully work.

**Comment by Brando47** [comment]
Yes I've had trouble in the past getting bazarr to output stdout from scripts called by the post processing script, I'd recommend perhaps creating your own little log file as a way to debug it. As an example: `/config/sub-clean.sh "$1" >> /config/mybazarr.log`

Another option would be to just use sub-clean.sh as you were previously, make sure to pass it in {{episode}} as the second option, then edit that script to include ffsubsync (add it to the end). That should at least get your sub-clean output sent to the bazarr logs. 

I'd recommend using the full path to your commands rather than relative paths, I'm not too sure what working directory the script is running from when it is invoked by bazarr. Are you using docker?

**Comment by brianspilner01** [comment]
Yes I've had trouble in the past getting bazarr to output stdout from scripts called by the post processing script, I'd recommend perhaps creating your own little log file as a way to debug it. As an example: `/config/sub-clean.sh "$1" >> /config/mybazarr.log`

Another option would be to just use sub-clean.sh as you were previously, make sure to pass it in {{episode}} as the second option, then edit that script to include ffsubsync (add it to the end). That should at least get your sub-clean output sent to the bazarr logs.

I'd recommend using the full path to your commands rather than relative paths, I'm not too sure what working directory the script is running from when it is invoked by bazarr. Are you using docker?

**Comment by Shawn9347** [comment]
I am using docker. I think I figured it out. 

![image](https://user-images.githubusercontent.com/48714886/114295340-f2938400-9aa4-11eb-92d1-2d18b58746bd.png)

And this is the script

![image](https://user-images.githubusercontent.com/48714886/114295353-00490980-9aa5-11eb-80f5-a6a782c0dd49.png)

I am using this docker image: https://hub.docker.com/r/sekkr1/bazarr-subsync
that docker image install linuxserver bazarr image but also ffsubsync inside the container. I found out that the command "ffsubsync" isn't available through the script in bazarr. So this docker image fixes that. 

I think everything is working but I want to debug ffsubsync in a log file. Where do I put that line for the logs?

![image](https://user-images.githubusercontent.com/48714886/114295400-4c944980-9aa5-11eb-9489-6154a194dfdf.png)

Is this right?

![image](https://user-images.githubusercontent.com/48714886/114295451-a0069780-9aa5-11eb-8f10-dd2b64099ad4.png)

**Comment by Shawn9347** [comment]
There is actually a command in ffsubsync to log files. 

![image](https://user-images.githubusercontent.com/48714886/114296379-6d5f9d80-9aab-11eb-9ddf-9112347de503.png)

But it's not working. So that would mean the command is not doing anything. Althrough the echo on the bottom is executed.

**Comment by Shawn9347** [comment]
I got it working!!!

![image](https://user-images.githubusercontent.com/48714886/114300615-73607900-9ac1-11eb-9222-1e027a8a9b7f.png)

Very rarely though your script is a little bit too good. 

I found that this line "Phase-lock 99%. Link is stable." was removed by the script. I looked at the script and I think it's got to do something with the word "link". Would you mind taking a look at your script once again? It happened a few other times but I don't have the logs anymore and I don't remember what line was removed.

**Comment by brianspilner01** [comment]
Glad you got it sorted :) 

It is fairly hard to find the balance between false positives and efficient removal of ads. I encourage people to adapt the regex to suit their own needs. In your case you could just remove "link" and one of the adjoining "or" pipe symbols `|` for that specific case, at the cost of allowing some ads to potentially seep through. If you're not 100% happy I'd recommend taking a look at sub-clean-with-trash.sh (back up the original srt file to a "trash" folder) or sub-clean-interactive.sh (manually control what gets removed) so you can keep a closer eye on it.

**Comment by Shawn9347** [comment]
Yea I added some statements of my own to the script. Some names weren't removed but I always make sure it's a word that will absolutely never be a word in a sentence in the movie. Something like "Филмотека" xDDDD I actually found this one in one of my subs.

**Comment by brianspilner01** [comment]
Sounds like you're all over it! Happy subtitling my friend!

**Comment by Shawn9347** [comment]
Talk to you later! bye
